on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker://dkhamsing/awesome_bot:latest
      with:
        args: --allow-redirect --allow-dupe --request-delay 1 --white-list www.vagrantup.com README.md
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: ab-results
        path: ab-results-README.md-filtered.json
